name: github pages deploy

on:
  push:
    branches:
    - master
    paths:
      - "index.md"
      - ".vitepress/**"
      - ".github/workflows/pages-deploy.yml"
  pull_request:
    branched:
    - master
    paths:
      - "index.md"
      - ".vitepress/**"
      - ".github/workflows/pages-deploy.yml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Node.js enviroments deploy
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: npm

    - name: Install package from package.json
      run: npm install

    - name: Exec build
      run: npm run docs:build
    
    - name: Add nojekyll
      run: touch ./out/.nojekyll

    - name: artifact upload
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./vitepress/dist

  deploy:
    environment:
      name: github-pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy github pages
        id: deployment
        uses: actions/deploy-pages@v2
