name: github pages deploy

on:
  push:
    branches:
    - master
    paths:
      - "pages/**"
      - ".github/worklows/pages-deploy.yml"
  pull_request:
    branched:
    - master
    paths:
      - "pages/**"
      - ".github/worklows/pages-deploy.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Node.js enviroments deploy
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: npm

    - name: Install package from package.json
      run: npm install

    - name: Exec build
      run: npm run build
    
    - name: Add nojekyll
      run: touch ./out/.nojekyll

    - name: artifact upload
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./out

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy github pages
        uses: actions/deploy-pages@v2
