name: github pages deploy

on:
  pull_request:
    branches:
    - master
    types:
    - closed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci-reuse:
    name: Build vitepress static content
    uses: ./.github/workflows/pages-integration.yml

  deploy:
    name: deploy pages build by vitepress
    needs: ci-reuse
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
    - name: Deploy github pages
      id: deployment
      uses: actions/deploy-pages@v2
